language: php
php:
    - "hhvm"
    - "hhvm-nightly"
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
before_script:
    - composer self-update
    - composer install --prefer-source
script:
    - composer test
